-- Lafarge Onboarding Service Database Schema
-- PostgreSQL Database Creation Script

-- Create database (run this separately if needed)
-- CREATE DATABASE "LafargeOnboardingDb";

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ASP.NET Core Identity Tables

-- AspNetRoles table
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone DEFAULT NOW(),
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

-- AspNetUsers table
CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "FirstName" character varying(100) NOT NULL DEFAULT '',
    "LastName" character varying(100) NOT NULL DEFAULT '',
    "Role" character varying(50) NOT NULL DEFAULT 'LOCAL_HIRE',
    "Department" text,
    "OnboardingStatus" text NOT NULL DEFAULT 'NotStarted',
    "CreatedAt" timestamp with time zone DEFAULT NOW(),
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

-- AspNetUserRoles table
CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- AspNetUserClaims table
CREATE TABLE "AspNetUserClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- AspNetUserLogins table
CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- AspNetUserTokens table
CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

-- AspNetRoleClaims table
CREATE TABLE "AspNetRoleClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

-- OnboardingDocuments table
CREATE TABLE "OnboardingDocuments" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FileName" character varying(500),
    "FilePath" character varying(1000),
    "Content" text,
    "ContentHeading" character varying(500),
    "ContentSubHeading" character varying(500),
    "BodyContentFileType" text,
    "BodyFilePath" text,
    "BodyContent" text,
    "ImageFilePath" text,
    "ImageFileType" text,
    "UploadedAt" timestamp with time zone DEFAULT NOW(),
    "UploadedBy" character varying(100),
    CONSTRAINT "PK_OnboardingDocuments" PRIMARY KEY ("Id")
);

-- Create indexes for better performance
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

-- Insert default roles
INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "Description", "CreatedAt") VALUES
('1', 'LOCAL_HIRE', 'LOCAL_HIRE', 'Local hire role', NOW()),
('2', 'EXPAT', 'EXPAT', 'Expat role', NOW()),
('3', 'VISITOR', 'VISITOR', 'Visitor role', NOW()),
('4', 'HR_ADMIN', 'HR_ADMIN', 'HR Admin role', NOW());

-- Create __EFMigrationsHistory table for Entity Framework
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);