CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AllContacts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Category" character varying(50) NOT NULL,
    "Data" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_AllContacts" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Description" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Role" character varying(50) NOT NULL,
    "StaffProfilePicture" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "ActiveStatus" boolean NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Contacts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "Phone" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id")
);

CREATE TABLE "Etiquettes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RegionalInfo" text NOT NULL,
    "FirstImpression" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Etiquettes" PRIMARY KEY ("Id")
);

CREATE TABLE "LocalHireInfos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WhoWeAre" text NOT NULL,
    "FootprintSummary" text NOT NULL,
    "Plants" text NOT NULL,
    "ReadyMix" text NOT NULL,
    "Depots" text NOT NULL,
    "CultureSummary" text NOT NULL,
    "Pillars" text NOT NULL,
    "Innovation" text NOT NULL,
    "HuaxinSpirit" text NOT NULL,
    "RespectfulWorkplaces" text NOT NULL,
    "Introduction" text NOT NULL,
    "CountryFacts" text NOT NULL,
    "InterestingFacts" text NOT NULL,
    "Holidays" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_LocalHireInfos" PRIMARY KEY ("Id")
);

CREATE TABLE "OnboardingDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName" character varying(500),
    "FilePath" character varying(1000),
    "Content" text,
    "ContentHeading" character varying(500),
    "ContentSubHeading" character varying(500),
    "BodyContentFileType" text,
    "BodyFilePath" text,
    "BodyContent" text,
    "ImageFilePath" text,
    "ImageFileType" text,
    "UploadedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UploadedBy" character varying(100),
    CONSTRAINT "PK_OnboardingDocuments" PRIMARY KEY ("Id")
);

CREATE TABLE "OnboardingPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BuddyDetails" text NOT NULL,
    "BuddyActivities" text NOT NULL,
    "ChecklistSummary" text NOT NULL,
    "Timeline" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_OnboardingPlans" PRIMARY KEY ("Id")
);

CREATE TABLE "WelcomeMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CeoName" character varying(200) NOT NULL,
    "CeoTitle" character varying(200) NOT NULL,
    "CeoImageUrl" character varying(500) NOT NULL,
    "CeoMessage" text NOT NULL,
    "HrName" character varying(200) NOT NULL,
    "HrTitle" character varying(200) NOT NULL,
    "HrImageUrl" character varying(500) NOT NULL,
    "HrMessage" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_WelcomeMessages" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "CreatedAt", "Description", "Name", "NormalizedName")
VALUES ('1', NULL, TIMESTAMPTZ '2025-11-13T10:33:03.206226Z', 'Local hire role', 'LOCAL_HIRE', 'LOCAL_HIRE');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "CreatedAt", "Description", "Name", "NormalizedName")
VALUES ('2', NULL, TIMESTAMPTZ '2025-11-13T10:33:03.206228Z', 'Expat role', 'EXPAT', 'EXPAT');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "CreatedAt", "Description", "Name", "NormalizedName")
VALUES ('3', NULL, TIMESTAMPTZ '2025-11-13T10:33:03.206228Z', 'Visitor role', 'VISITOR', 'VISITOR');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "CreatedAt", "Description", "Name", "NormalizedName")
VALUES ('4', NULL, TIMESTAMPTZ '2025-11-13T10:33:03.206229Z', 'HR Admin role', 'HR_ADMIN', 'HR_ADMIN');

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251113103303_InitialCreate', '8.0.10');

COMMIT;

